"""
Django settings for foxcons_oidc_bridge project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_csv(name, default=None):
    value = os.environ.get(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


def env_str(name, default=''):
    return os.environ.get(name, default)


def env_optional_tuple(name):
    value = os.environ.get(name)
    if not value:
        return None
    parts = [item.strip() for item in value.split(',', 1)]
    if len(parts) != 2 or not parts[0] or not parts[1]:
        return None
    return parts[0], parts[1]


IS_TESTING = 'test' in sys.argv

# Load OIDC RSA key if available
OIDC_RSA_PRIVATE_KEY = os.environ.get('OIDC_RSA_PRIVATE_KEY', None)
if not OIDC_RSA_PRIVATE_KEY:
    # Try loading from file for development
    oidc_key_file = BASE_DIR / '.oidc_rsa_key.txt'
    if oidc_key_file.exists():
        OIDC_RSA_PRIVATE_KEY = oidc_key_file.read_text()
elif '\\n' in OIDC_RSA_PRIVATE_KEY:
    OIDC_RSA_PRIVATE_KEY = OIDC_RSA_PRIVATE_KEY.replace('\\n', '\n')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_str('SECRET_KEY', 'django-insecure-*n8f)0pt8)0cv3*)zc@(qmy^t3a4bvlvp9y*%pimg1=(7ey&%)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=IS_TESTING)

ALLOWED_HOSTS = env_csv(
    'ALLOWED_HOSTS',
    default=['127.0.0.1', 'localhost', 'testserver'] if DEBUG else [],
)

if not DEBUG:
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured('Set SECRET_KEY in the environment when DEBUG is False.')
    if not OIDC_RSA_PRIVATE_KEY:
        raise ImproperlyConfigured('Set OIDC_RSA_PRIVATE_KEY in the environment when DEBUG is False.')
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured('Set ALLOWED_HOSTS in the environment when DEBUG is False.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oauth2_provider',
    'instances',
    'foxcons',
    'bridge_oidc',
]

OAUTH2_PROVIDER = {
    'OIDC_ENABLED': True,
    'OIDC_RSA_PRIVATE_KEY': OIDC_RSA_PRIVATE_KEY,
    'PKCE_REQUIRED': True,
    'ACCESS_TOKEN_EXPIRE_SECONDS': int(env_str('ACCESS_TOKEN_EXPIRE_SECONDS', '3600')),
    'REFRESH_TOKEN_EXPIRE_SECONDS': int(env_str('REFRESH_TOKEN_EXPIRE_SECONDS', str(7 * 24 * 3600))),
    'OAUTH2_VALIDATOR_CLASS': 'bridge_oidc.validators.BridgeOAuth2Validator',
    'SCOPES': {
        'openid': 'OpenID Connect scope',
        'profile': 'Profile scope',
        'email': 'Email scope',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'bridge_oidc.middleware.BridgeAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'bridge_oidc.auth.BridgeSessionBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'foxcons_oidc_bridge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'foxcons_oidc_bridge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(env_str('DATABASE_PATH', str(BASE_DIR / 'db.sqlite3'))),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('pl', 'Polski'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_USE_FINDERS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/bridge/login/'
LOGOUT_URL = '/bridge/logout/'

CSRF_TRUSTED_ORIGINS = env_csv('CSRF_TRUSTED_ORIGINS', default=[])

SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SESSION_COOKIE_HTTPONLY = env_bool('SESSION_COOKIE_HTTPONLY', default=True)
SESSION_COOKIE_SAMESITE = env_str('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = env_str('CSRF_COOKIE_SAMESITE', 'Lax')

SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SECURE_PROXY_SSL_HEADER = env_optional_tuple('SECURE_PROXY_SSL_HEADER')

BRIDGE_LOGIN_RATE_LIMIT_ATTEMPTS = int(env_str('BRIDGE_LOGIN_RATE_LIMIT_ATTEMPTS', '10'))
BRIDGE_LOGIN_RATE_LIMIT_WINDOW_SECONDS = int(env_str('BRIDGE_LOGIN_RATE_LIMIT_WINDOW_SECONDS', '300'))
