# Generated by Django 5.2.12 on 2026-03-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_oidc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoxconsTokenClaims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('claims', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
