# Generated by Django 5.2.12 on 2026-03-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foxconsinstance',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional icon displayed on the login page event selector (recommended: square, min 64×64 px).', null=True, upload_to='instance_icons/'),
        ),
    ]
