# Generated by Django 5.2.12 on 2026-03-29 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_foxconsinstance_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='foxconsinstance',
            name='theme_primary',
            field=models.CharField(default='#fca5a5', help_text='Primary motif color for this event (HEX), used in hero gradients.', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a valid HEX color like #ef4444', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='foxconsinstance',
            name='theme_secondary',
            field=models.CharField(default='#ef4444', help_text='Secondary motif color for this event (HEX), used for buttons and accents.', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a valid HEX color like #ef4444', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
