# Generated by Django 5.2.12 on 2026-03-29 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_foxconsinstance_theme_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foxconsinstance',
            name='theme_text',
            field=models.CharField(default='#2b0a0a', help_text='Text color used on bright hero sections for this event motif (HEX).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a valid HEX color like #ef4444', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
